name: New Editor Version 🗔

on:
  repository_dispatch:
    types: [new_legacy_editor_image_requested]

# Further reading:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event
# https://developer.github.com/webhooks/event-payloads/#repository_dispatch

jobs:
  buildImage:
    name: "🛠 Build gaeelbradshaw/editor (${{ matrix.targetPlatform }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - base # Base is a special name, which indicates that no modules are installed, like with linux-mono on ubuntu
          # - linux-il2cpp
          # - windows-mono
          # - mac-mono
          # - ios
          - android
          # - webgl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      ###########################
      #        Variables        #
      ###########################
      - name: Show hook input
        run: |
          echo "Event ${{ github.event.event_type }}"
          echo "jobId: ${{ github.event.client_payload.jobId }}"
          echo "Unity editor version: ${{ github.event.client_payload.editorVersion }}"
          echo "Unity changeset: ${{ github.event.client_payload.changeSet }}"
          echo "repoVersion (full): ${{ github.event.client_payload.repoVersionFull }}"
          echo "repoVersion (only minor and major): ${{ github.event.client_payload.repoVersionMinor }}"
          echo "repoVersion (only major): ${{ github.event.client_payload.repoVersionMajor }}"
      ###########################
      #          Setup          #
      ###########################
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      ###########################
      #    Free disk space   #
      ###########################
      - name: Free disk space
        run: .github/workflows/scripts/free_disk_space.sh
      ###########################
      #   Pull previous images  #
      ###########################
      - name: Pull base image (must exist)
        run: docker pull gaeelbradshaw/base:${{ github.event.client_payload.repoVersionFull }}
      - name: Pull hub image (must exist)
        run: docker pull gaeelbradshaw/hub:${{ github.event.client_payload.repoVersionFull }}
      ###########################
      #       Editor image      #
      ###########################
      - name: Build and publish
        uses: docker/build-push-action@v2
        id: build_editor_image
        continue-on-error: true
        with:
          context: .
          file: ./editor/Dockerfile
          build-args: |
            hubImage=gaeelbradshaw/hub:${{ github.event.client_payload.repoVersionFull }}
            baseImage=gaeelbradshaw/base:${{ github.event.client_payload.repoVersionFull }}
            version=${{ github.event.client_payload.editorVersion }}
            changeSet=${{ github.event.client_payload.changeSet }}
            module=${{ matrix.targetPlatform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            gaeelbradshaw/editor:${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionFull }}
            gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMinor }}
            gaeelbradshaw/editor:${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMinor }}
            gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMajor }}
            gaeelbradshaw/editor:${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMajor }}
            gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionFull }}
          ### Warning: If we once publish latest, we will have to do it forever. Lets not do that unless it's needed ###
          ### Another warning: order is important: We go from specific to unspecific with the exception of the most specific tag which is used to check if the image is already there ###
      ###########################
      #     Retry the above     #
      ###########################
      - name: Build and publish (retry)
        uses: docker/build-push-action@v2
        if: steps.build_editor_image.outcome=='failure'
        id: build_editor_image_retry
        with:
          context: .
          file: ./editor/Dockerfile
          build-args: |
            hubImage=gaeelbradshaw/hub:${{ github.event.client_payload.repoVersionFull }}
            baseImage=gaeelbradshaw/base:${{ github.event.client_payload.repoVersionFull }}
            version=${{ github.event.client_payload.editorVersion }}
            changeSet=${{ github.event.client_payload.changeSet }}
            module=${{ matrix.targetPlatform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            gaeelbradshaw/editor:${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionFull }}
            gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMinor }}
            gaeelbradshaw/editor:${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMinor }}
            gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMajor }}
            gaeelbradshaw/editor:${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionMajor }}
            gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionFull }}
          ### Warning: If we once publish latest, we will have to do it forever. Lets not do that unless it's needed ###
          ### Another warning: order is important: We go from specific to unspecific with the exception of the most specific tag which is used to check if the image is already there ###
      ###########################
      #   Inspect publication   #
      ###########################
      - name: Inspect
        run: |
          docker buildx imagetools inspect gaeelbradshaw/editor:ubuntu-${{ github.event.client_payload.editorVersion }}-${{ matrix.targetPlatform }}-${{ github.event.client_payload.repoVersionFull }}
      - name: Image digest
        id: image-digest
        run: |
          [ '${{ steps.build_editor_image.outcome }}'       = 'success' ] && echo "::set-output name=digest::${{ steps.build_editor_image.outputs.digest }}" || :
          [ '${{ steps.build_editor_image_retry.outcome }}' = 'success' ] && echo "::set-output name=digest::${{ steps.build_editor_image_retry.outputs.digest }}" || :
      ###########################
      #         Metrics         #
      ###########################
      - name: Disk space after
        if: always()
        run: df -h
