name: New Base Version ⛭

on:
  repository_dispatch:
    types: [new_base_image_requested]

# Further reading:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event
# https://developer.github.com/webhooks/event-payloads/#repository_dispatch

jobs:
  build:
    name: "🛠 Build gaeelbradshaw/base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      ###########################
      #        Variables        #
      ###########################
      - name: Show hook input
        run: |
          echo "Event ${{ github.event.event_type }}"
          echo "jobId: ${{ github.event.client_payload.jobId }}"
          echo "repoVersion (full): ${{ github.event.client_payload.repoVersionFull }}"
          echo "repoVersion (only minor and major): ${{ github.event.client_payload.repoVersionMinor }}"
          echo "repoVersion (only major): ${{ github.event.client_payload.repoVersionMajor }}"
      ###########################
      #          Setup          #
      ###########################
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.event.client_payload.repoVersionFull }}-${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ github.event.client_payload.repoVersionFull }}-${{ runner.os }}-buildx-base
            ${{ github.event.client_payload.repoVersionFull }}-${{ runner.os }}-buildx-
      ###########################
      #        Base image       #
      ###########################
      - name: Build and publish
        uses: docker/build-push-action@v2
        id: build_base_image
        with:
          context: .
          file: ./base/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            gaeelbradshaw/base:ubuntu-${{ github.event.client_payload.repoVersionFull }}
            gaeelbradshaw/base:${{ github.event.client_payload.repoVersionFull }}
            gaeelbradshaw/base:ubuntu-${{ github.event.client_payload.repoVersionMinor }}
            gaeelbradshaw/base:${{ github.event.client_payload.repoVersionMinor }}
            gaeelbradshaw/base:ubuntu-${{ github.event.client_payload.repoVersionMajor }}
            gaeelbradshaw/base:${{ github.event.client_payload.repoVersionMajor }}
            gaeelbradshaw/base:ubuntu-latest
            gaeelbradshaw/base:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect gaeelbradshaw/base:ubuntu-${{ github.event.client_payload.repoVersionFull }}
      - name: Image digest
        run: echo ${{ steps.build_base_image.outputs.digest }}
